/** @type {import('tailwindcss').Config} */
export default {
        content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
        theme: {
          extend: {
            colors: {
                    "surface-container-low": "#f6f3f2",
                    "outline-variant": "#d2c5ab",
                    "inverse-on-surface": "#f3f0ef",
                    "surface-container-highest": "#e5e2e1",
                    "secondary-fixed": "#e5e2e1",
                    "on-surface": "#1c1b1b",
                    "on-error-container": "#93000a",
                    "on-tertiary": "#ffffff",
                    "on-secondary-fixed-variant": "#474746",
                    "inverse-primary": "#f1c100",
                    "tertiary-fixed-dim": "#c6c6c7",
                    "surface-container-high": "#eae7e7",
                    "error-container": "#ffdad6",
                    "outline": "#80765f",
                    "on-background": "#1c1b1b",
                    "primary-fixed-dim": "#f1c100",
                    "on-primary-fixed": "#241a00",
                    "secondary-fixed-dim": "#c8c6c5",
                    "on-secondary-fixed": "#1c1b1b",
                    "primary-fixed": "#ffe08b",
                    "surface-container": "#f0eded",
                    "on-error": "#ffffff",
                    "on-primary-container": "#6f5700",
                    "secondary-container": "#e2dfde",
                    "secondary": "#5f5e5e",
                    "on-tertiary-fixed": "#1a1c1c",
                    "on-tertiary-container": "#595a5b",
                    "surface-bright": "#fcf9f8",
                    "tertiary": "#5d5f5f",
                    "on-tertiary-fixed-variant": "#454747",
                    "surface-container-lowest": "#ffffff",
                    "inverse-surface": "#313030",
                    "surface-variant": "#e5e2e1",
                    "tertiary-container": "#d2d2d2",
                    "surface-tint": "#745b00",
                    "tertiary-fixed": "#e2e2e2",
                    "surface-dim": "#dcd9d9",
                    "on-surface-variant": "#4e4632",
                    "on-secondary": "#ffffff",
                    "on-primary-fixed-variant": "#584400",
                    "error": "#ba1a1a",
                    "on-primary": "#ffffff",
                    "primary-container": "#ffcc00",
                    "surface": "#fcf9f8",
                    "background": "#fcf9f8",
                    "primary": "#745b00",
                    "on-secondary-container": "#636262"
            },
            borderRadius: {
                    "DEFAULT": "0px",
                    "lg": "0px",
                    "xl": "0px",
                    "full": "9999px"
            },
            spacing: {
                    "gutter": "32px",
                    "container-max": "1280px",
                    "margin": "40px",
                    "block-padding": "64px",
                    "base": "8px"
            },
          },
        },
        plugins: [],
      }